export const tagsData = [
  { id: 1, name: "Cool", results: "350 results" },
  { id: 2, name: "Beautiful", results: "210 results" },
  { id: 3, name: "Easy", results: "190 results" },
  { id: 4, name: "Summary", results: "105 results" },
  { id: 5, name: "Hot", results: "80 results" },
  { id: 6, name: "Passage Specific", results: "50 questions" },
  { id: 7, name: "Very long taaaaaaag name", results: "50 questions" },
  { id: 8, name: "Tag", results: "50 questions" },
  { id: 9, name: "Tag", results: "50 questions" },
  { id: 10, name: "Tag", results: "50 questions" },
  { id: 11, name: "Tag", results: "50 questions" },
  { id: 12, name: "Tag", results: "50 questions" },
  { id: 13, name: "Tag", results: "50 questions" },
  { id: 14, name: "Tag", results: "50 questions" },
  { id: 15, name: "Tag", results: "50 questions" },
  { id: 16, name: "Tag", results: "50 questions" },
  { id: 17, name: "Tag", results: "50 questions" },
  { id: 18, name: "Tag", results: "50 questions" },
  { id: 19, name: "Tag", results: "50 questions" },
  { id: 20, name: "Tag", results: "50 questions" },
  { id: 21, name: "Tag", results: "50 questions" },
  { id: 22, name: "Tag", results: "50 questions" },
  { id: 23, name: "Tag", results: "50 questions" },
  { id: 24, name: "Tag", results: "50 questions" },
  { id: 25, name: "Tag", results: "50 questions" },
  { id: 26, name: "Tag", results: "50 questions" },
  { id: 27, name: "Tag", results: "50 questions" },
  { id: 28, name: "Tag", results: "50 questions" },
  { id: 29, name: "Tag", results: "50 questions" },
  { id: 30, name: "Tag", results: "50 questions" },
];
